// Контракт публичного API GophKeeper по gRPC.
// Смысл полей совпадает с доменными моделями в internal/model.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gophkeeper.proto

package gophkeeperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Область выборки для ListSecrets: активные, только корзина (мягко удалённые) или все.
type SecretListScope int32

const (
	SecretListScope_SECRET_LIST_SCOPE_UNSPECIFIED  SecretListScope = 0
	SecretListScope_SECRET_LIST_SCOPE_ACTIVE_ONLY  SecretListScope = 1
	SecretListScope_SECRET_LIST_SCOPE_DELETED_ONLY SecretListScope = 2
	SecretListScope_SECRET_LIST_SCOPE_ALL          SecretListScope = 3
)

// Enum value maps for SecretListScope.
var (
	SecretListScope_name = map[int32]string{
		0: "SECRET_LIST_SCOPE_UNSPECIFIED",
		1: "SECRET_LIST_SCOPE_ACTIVE_ONLY",
		2: "SECRET_LIST_SCOPE_DELETED_ONLY",
		3: "SECRET_LIST_SCOPE_ALL",
	}
	SecretListScope_value = map[string]int32{
		"SECRET_LIST_SCOPE_UNSPECIFIED":  0,
		"SECRET_LIST_SCOPE_ACTIVE_ONLY":  1,
		"SECRET_LIST_SCOPE_DELETED_ONLY": 2,
		"SECRET_LIST_SCOPE_ALL":          3,
	}
)

func (x SecretListScope) Enum() *SecretListScope {
	p := new(SecretListScope)
	*p = x
	return p
}

func (x SecretListScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretListScope) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (SecretListScope) Type() protoreflect.EnumType {
	return &file_gophkeeper_proto_enumTypes[0]
}

func (x SecretListScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretListScope.Descriptor instead.
func (SecretListScope) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

// Запрос Ping: пустое сообщение своего типа — при появлении параметров (например locale)
// добавляются новые поля с номерами, старые клиенты по правилам proto3 их игнорируют.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

// Ответ на Ping: можно расширять (версия сервера и т.д.).
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Короткая строка, например "ok".
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Ответ на удаление секрета: пока без полей; при необходимости сюда добавляют, например,
// идентификатор асинхронной операции или время удаления — номера полей не пересекаются с «чужими» типами.
type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{2}
}

// Ответ на удаление вложения — отдельный тип для независимого расширения.
type DeleteAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentResponse) Reset() {
	*x = DeleteAttachmentResponse{}
	mi := &file_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentResponse) ProtoMessage() {}

func (x *DeleteAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email пользователя (уникален на сервере).
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RefreshTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refresh-токен, выданный ранее при Login/Register/Refresh.
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Ответ с токенами (как в model.AuthResponse).
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salt          string                 `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *AuthResponse) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Краткая информация о секрете для списков и синхронизации.
type SecretSummary struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentSecretVersionId string                 `protobuf:"bytes,2,opt,name=current_secret_version_id,json=currentSecretVersionId,proto3" json:"current_secret_version_id,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Для записей в корзине (мягкое удаление); для активных не задаётся.
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// Название (ciphertext, тот же алгоритм, что data_encrypted); пусто для старых данных.
	TitleEncrypted []byte `protobuf:"bytes,5,opt,name=title_encrypted,json=titleEncrypted,proto3" json:"title_encrypted,omitempty"`
	// Время создания записи секрета.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSummary) Reset() {
	*x = SecretSummary{}
	mi := &file_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSummary) ProtoMessage() {}

func (x *SecretSummary) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSummary.ProtoReflect.Descriptor instead.
func (*SecretSummary) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *SecretSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretSummary) GetCurrentSecretVersionId() string {
	if x != nil {
		return x.CurrentSecretVersionId
	}
	return ""
}

func (x *SecretSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SecretSummary) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *SecretSummary) GetTitleEncrypted() []byte {
	if x != nil {
		return x.TitleEncrypted
	}
	return nil
}

func (x *SecretSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListScope     SecretListScope        `protobuf:"varint,1,opt,name=list_scope,json=listScope,proto3,enum=gophkeeper.v1.SecretListScope" json:"list_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *ListSecretsRequest) GetListScope() SecretListScope {
	if x != nil {
		return x.ListScope
	}
	return SecretListScope_SECRET_LIST_SCOPE_UNSPECIFIED
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretSummary       `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretSummary {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type GetSecretRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SecretId              string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	IncludeVersionHistory bool                   `protobuf:"varint,2,opt,name=include_version_history,json=includeVersionHistory,proto3" json:"include_version_history,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *GetSecretRequest) GetIncludeVersionHistory() bool {
	if x != nil {
		return x.IncludeVersionHistory
	}
	return false
}

// Полный секрет: метаданные + текущая версия и опционально история.
type Secret struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentSecretVersionId string                 `protobuf:"bytes,3,opt,name=current_secret_version_id,json=currentSecretVersionId,proto3" json:"current_secret_version_id,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CurrentVersion         *SecretVersion         `protobuf:"bytes,7,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	SecretVersions         []*SecretVersion       `protobuf:"bytes,8,rep,name=secret_versions,json=secretVersions,proto3" json:"secret_versions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Secret) GetCurrentSecretVersionId() string {
	if x != nil {
		return x.CurrentSecretVersionId
	}
	return ""
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Secret) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Secret) GetCurrentVersion() *SecretVersion {
	if x != nil {
		return x.CurrentVersion
	}
	return nil
}

func (x *Secret) GetSecretVersions() []*SecretVersion {
	if x != nil {
		return x.SecretVersions
	}
	return nil
}

type SecretVersion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretId          string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Version           int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	DataFormatVersion int32                  `protobuf:"varint,4,opt,name=data_format_version,json=dataFormatVersion,proto3" json:"data_format_version,omitempty"`
	DataEncrypted     []byte                 `protobuf:"bytes,5,opt,name=data_encrypted,json=dataEncrypted,proto3" json:"data_encrypted,omitempty"`
	DataSize          int32                  `protobuf:"varint,6,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// Название в списке (ciphertext); пусто для старых версий.
	TitleEncrypted []byte `protobuf:"bytes,10,opt,name=title_encrypted,json=titleEncrypted,proto3" json:"title_encrypted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SecretVersion) Reset() {
	*x = SecretVersion{}
	mi := &file_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretVersion) ProtoMessage() {}

func (x *SecretVersion) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretVersion.ProtoReflect.Descriptor instead.
func (*SecretVersion) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *SecretVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretVersion) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SecretVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretVersion) GetDataFormatVersion() int32 {
	if x != nil {
		return x.DataFormatVersion
	}
	return 0
}

func (x *SecretVersion) GetDataEncrypted() []byte {
	if x != nil {
		return x.DataEncrypted
	}
	return nil
}

func (x *SecretVersion) GetDataSize() int32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *SecretVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretVersion) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SecretVersion) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *SecretVersion) GetTitleEncrypted() []byte {
	if x != nil {
		return x.TitleEncrypted
	}
	return nil
}

type CreateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DataEncrypted     []byte                 `protobuf:"bytes,1,opt,name=data_encrypted,json=dataEncrypted,proto3" json:"data_encrypted,omitempty"`
	DataFormatVersion int32                  `protobuf:"varint,2,opt,name=data_format_version,json=dataFormatVersion,proto3" json:"data_format_version,omitempty"`
	TitleEncrypted    []byte                 `protobuf:"bytes,3,opt,name=title_encrypted,json=titleEncrypted,proto3" json:"title_encrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *CreateSecretRequest) GetDataEncrypted() []byte {
	if x != nil {
		return x.DataEncrypted
	}
	return nil
}

func (x *CreateSecretRequest) GetDataFormatVersion() int32 {
	if x != nil {
		return x.DataFormatVersion
	}
	return 0
}

func (x *CreateSecretRequest) GetTitleEncrypted() []byte {
	if x != nil {
		return x.TitleEncrypted
	}
	return nil
}

type UpdateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecretId          string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	DataEncrypted     []byte                 `protobuf:"bytes,2,opt,name=data_encrypted,json=dataEncrypted,proto3" json:"data_encrypted,omitempty"`
	DataFormatVersion int32                  `protobuf:"varint,3,opt,name=data_format_version,json=dataFormatVersion,proto3" json:"data_format_version,omitempty"`
	TitleEncrypted    []byte                 `protobuf:"bytes,4,opt,name=title_encrypted,json=titleEncrypted,proto3" json:"title_encrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *UpdateSecretRequest) GetDataEncrypted() []byte {
	if x != nil {
		return x.DataEncrypted
	}
	return nil
}

func (x *UpdateSecretRequest) GetDataFormatVersion() int32 {
	if x != nil {
		return x.DataFormatVersion
	}
	return 0
}

func (x *UpdateSecretRequest) GetTitleEncrypted() []byte {
	if x != nil {
		return x.TitleEncrypted
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type ListSecretVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsRequest) Reset() {
	*x = ListSecretVersionsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsRequest) ProtoMessage() {}

func (x *ListSecretVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{17}
}

func (x *ListSecretVersionsRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type ListSecretVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*SecretVersion       `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsResponse) Reset() {
	*x = ListSecretVersionsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsResponse) ProtoMessage() {}

func (x *ListSecretVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{18}
}

func (x *ListSecretVersionsResponse) GetVersions() []*SecretVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetSecretVersionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SecretId        string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	SecretVersionId string                 `protobuf:"bytes,2,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSecretVersionRequest) Reset() {
	*x = GetSecretVersionRequest{}
	mi := &file_gophkeeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretVersionRequest) ProtoMessage() {}

func (x *GetSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*GetSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{19}
}

func (x *GetSecretVersionRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *GetSecretVersionRequest) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

type DeleteSecretVersionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SecretId        string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	SecretVersionId string                 `protobuf:"bytes,2,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteSecretVersionRequest) Reset() {
	*x = DeleteSecretVersionRequest{}
	mi := &file_gophkeeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretVersionRequest) ProtoMessage() {}

func (x *DeleteSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteSecretVersionRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *DeleteSecretVersionRequest) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

type DeleteSecretVersionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SecretVersionId string                 `protobuf:"bytes,1,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteSecretVersionResponse) Reset() {
	*x = DeleteSecretVersionResponse{}
	mi := &file_gophkeeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretVersionResponse) ProtoMessage() {}

func (x *DeleteSecretVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretVersionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretVersionResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteSecretVersionResponse) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

type RestoreSecretVersionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SecretId        string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	SecretVersionId string                 `protobuf:"bytes,2,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreSecretVersionRequest) Reset() {
	*x = RestoreSecretVersionRequest{}
	mi := &file_gophkeeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSecretVersionRequest) ProtoMessage() {}

func (x *RestoreSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*RestoreSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{22}
}

func (x *RestoreSecretVersionRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *RestoreSecretVersionRequest) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

type RestoreSecretVersionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SecretVersionId string                 `protobuf:"bytes,1,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreSecretVersionResponse) Reset() {
	*x = RestoreSecretVersionResponse{}
	mi := &file_gophkeeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSecretVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSecretVersionResponse) ProtoMessage() {}

func (x *RestoreSecretVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSecretVersionResponse.ProtoReflect.Descriptor instead.
func (*RestoreSecretVersionResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{23}
}

func (x *RestoreSecretVersionResponse) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

type AttachmentSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretVersionId   string                 `protobuf:"bytes,2,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	DataFormatVersion int32                  `protobuf:"varint,3,opt,name=data_format_version,json=dataFormatVersion,proto3" json:"data_format_version,omitempty"`
	InfoFormatVersion int32                  `protobuf:"varint,4,opt,name=info_format_version,json=infoFormatVersion,proto3" json:"info_format_version,omitempty"`
	InfoEncrypted     []byte                 `protobuf:"bytes,5,opt,name=info_encrypted,json=infoEncrypted,proto3" json:"info_encrypted,omitempty"`
	InfoSize          int32                  `protobuf:"varint,6,opt,name=info_size,json=infoSize,proto3" json:"info_size,omitempty"`
	DataSize          int32                  `protobuf:"varint,7,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttachmentSummary) Reset() {
	*x = AttachmentSummary{}
	mi := &file_gophkeeper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentSummary) ProtoMessage() {}

func (x *AttachmentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentSummary.ProtoReflect.Descriptor instead.
func (*AttachmentSummary) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{24}
}

func (x *AttachmentSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttachmentSummary) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

func (x *AttachmentSummary) GetDataFormatVersion() int32 {
	if x != nil {
		return x.DataFormatVersion
	}
	return 0
}

func (x *AttachmentSummary) GetInfoFormatVersion() int32 {
	if x != nil {
		return x.InfoFormatVersion
	}
	return 0
}

func (x *AttachmentSummary) GetInfoEncrypted() []byte {
	if x != nil {
		return x.InfoEncrypted
	}
	return nil
}

func (x *AttachmentSummary) GetInfoSize() int32 {
	if x != nil {
		return x.InfoSize
	}
	return 0
}

func (x *AttachmentSummary) GetDataSize() int32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *AttachmentSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Attachment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretVersionId   string                 `protobuf:"bytes,2,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	DataFormatVersion int32                  `protobuf:"varint,3,opt,name=data_format_version,json=dataFormatVersion,proto3" json:"data_format_version,omitempty"`
	InfoFormatVersion int32                  `protobuf:"varint,4,opt,name=info_format_version,json=infoFormatVersion,proto3" json:"info_format_version,omitempty"`
	InfoEncrypted     []byte                 `protobuf:"bytes,5,opt,name=info_encrypted,json=infoEncrypted,proto3" json:"info_encrypted,omitempty"`
	InfoSize          int32                  `protobuf:"varint,6,opt,name=info_size,json=infoSize,proto3" json:"info_size,omitempty"`
	DataEncrypted     []byte                 `protobuf:"bytes,7,opt,name=data_encrypted,json=dataEncrypted,proto3" json:"data_encrypted,omitempty"`
	DataSize          int32                  `protobuf:"varint,8,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_gophkeeper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{25}
}

func (x *Attachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attachment) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

func (x *Attachment) GetDataFormatVersion() int32 {
	if x != nil {
		return x.DataFormatVersion
	}
	return 0
}

func (x *Attachment) GetInfoFormatVersion() int32 {
	if x != nil {
		return x.InfoFormatVersion
	}
	return 0
}

func (x *Attachment) GetInfoEncrypted() []byte {
	if x != nil {
		return x.InfoEncrypted
	}
	return nil
}

func (x *Attachment) GetInfoSize() int32 {
	if x != nil {
		return x.InfoSize
	}
	return 0
}

func (x *Attachment) GetDataEncrypted() []byte {
	if x != nil {
		return x.DataEncrypted
	}
	return nil
}

func (x *Attachment) GetDataSize() int32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *Attachment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListAttachmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*ListAttachmentsRequest_SecretId
	//	*ListAttachmentsRequest_SecretVersionId
	Scope         isListAttachmentsRequest_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsRequest) Reset() {
	*x = ListAttachmentsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsRequest) ProtoMessage() {}

func (x *ListAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{26}
}

func (x *ListAttachmentsRequest) GetScope() isListAttachmentsRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ListAttachmentsRequest) GetSecretId() string {
	if x != nil {
		if x, ok := x.Scope.(*ListAttachmentsRequest_SecretId); ok {
			return x.SecretId
		}
	}
	return ""
}

func (x *ListAttachmentsRequest) GetSecretVersionId() string {
	if x != nil {
		if x, ok := x.Scope.(*ListAttachmentsRequest_SecretVersionId); ok {
			return x.SecretVersionId
		}
	}
	return ""
}

type isListAttachmentsRequest_Scope interface {
	isListAttachmentsRequest_Scope()
}

type ListAttachmentsRequest_SecretId struct {
	SecretId string `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3,oneof"`
}

type ListAttachmentsRequest_SecretVersionId struct {
	SecretVersionId string `protobuf:"bytes,2,opt,name=secret_version_id,json=secretVersionId,proto3,oneof"`
}

func (*ListAttachmentsRequest_SecretId) isListAttachmentsRequest_Scope() {}

func (*ListAttachmentsRequest_SecretVersionId) isListAttachmentsRequest_Scope() {}

type ListAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachments   []*AttachmentSummary   `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsResponse) Reset() {
	*x = ListAttachmentsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsResponse) ProtoMessage() {}

func (x *ListAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{27}
}

func (x *ListAttachmentsResponse) GetAttachments() []*AttachmentSummary {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type GetAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentRequest) Reset() {
	*x = GetAttachmentRequest{}
	mi := &file_gophkeeper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentRequest) ProtoMessage() {}

func (x *GetAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{28}
}

func (x *GetAttachmentRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

type CreateAttachmentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecretVersionId   string                 `protobuf:"bytes,1,opt,name=secret_version_id,json=secretVersionId,proto3" json:"secret_version_id,omitempty"`
	DataFormatVersion int32                  `protobuf:"varint,2,opt,name=data_format_version,json=dataFormatVersion,proto3" json:"data_format_version,omitempty"`
	InfoFormatVersion int32                  `protobuf:"varint,3,opt,name=info_format_version,json=infoFormatVersion,proto3" json:"info_format_version,omitempty"`
	InfoEncrypted     []byte                 `protobuf:"bytes,4,opt,name=info_encrypted,json=infoEncrypted,proto3" json:"info_encrypted,omitempty"`
	DataEncrypted     []byte                 `protobuf:"bytes,5,opt,name=data_encrypted,json=dataEncrypted,proto3" json:"data_encrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateAttachmentRequest) Reset() {
	*x = CreateAttachmentRequest{}
	mi := &file_gophkeeper_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentRequest) ProtoMessage() {}

func (x *CreateAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{29}
}

func (x *CreateAttachmentRequest) GetSecretVersionId() string {
	if x != nil {
		return x.SecretVersionId
	}
	return ""
}

func (x *CreateAttachmentRequest) GetDataFormatVersion() int32 {
	if x != nil {
		return x.DataFormatVersion
	}
	return 0
}

func (x *CreateAttachmentRequest) GetInfoFormatVersion() int32 {
	if x != nil {
		return x.InfoFormatVersion
	}
	return 0
}

func (x *CreateAttachmentRequest) GetInfoEncrypted() []byte {
	if x != nil {
		return x.InfoEncrypted
	}
	return nil
}

func (x *CreateAttachmentRequest) GetDataEncrypted() []byte {
	if x != nil {
		return x.DataEncrypted
	}
	return nil
}

type DeleteAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentRequest) Reset() {
	*x = DeleteAttachmentRequest{}
	mi := &file_gophkeeper_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentRequest) ProtoMessage() {}

func (x *DeleteAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteAttachmentRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\rgophkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x16\n" +
	"\x14DeleteSecretResponse\"\x1a\n" +
	"\x18DeleteAttachmentResponse\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x98\x01\n" +
	"\fAuthResponse\x12\x12\n" +
	"\x04salt\x18\x01 \x01(\tR\x04salt\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xb4\x02\n" +
	"\rSecretSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x19current_secret_version_id\x18\x02 \x01(\tR\x16currentSecretVersionId\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12'\n" +
	"\x0ftitle_encrypted\x18\x05 \x01(\fR\x0etitleEncrypted\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"S\n" +
	"\x12ListSecretsRequest\x12=\n" +
	"\n" +
	"list_scope\x18\x01 \x01(\x0e2\x1e.gophkeeper.v1.SecretListScopeR\tlistScope\"M\n" +
	"\x13ListSecretsResponse\x126\n" +
	"\asecrets\x18\x01 \x03(\v2\x1c.gophkeeper.v1.SecretSummaryR\asecrets\"g\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x126\n" +
	"\x17include_version_history\x18\x02 \x01(\bR\x15includeVersionHistory\"\xab\x03\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\x19current_secret_version_id\x18\x03 \x01(\tR\x16currentSecretVersionId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12E\n" +
	"\x0fcurrent_version\x18\a \x01(\v2\x1c.gophkeeper.v1.SecretVersionR\x0ecurrentVersion\x12E\n" +
	"\x0fsecret_versions\x18\b \x03(\v2\x1c.gophkeeper.v1.SecretVersionR\x0esecretVersions\"\xa4\x03\n" +
	"\rSecretVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12.\n" +
	"\x13data_format_version\x18\x04 \x01(\x05R\x11dataFormatVersion\x12%\n" +
	"\x0edata_encrypted\x18\x05 \x01(\fR\rdataEncrypted\x12\x1b\n" +
	"\tdata_size\x18\x06 \x01(\x05R\bdataSize\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12'\n" +
	"\x0ftitle_encrypted\x18\n" +
	" \x01(\fR\x0etitleEncrypted\"\x95\x01\n" +
	"\x13CreateSecretRequest\x12%\n" +
	"\x0edata_encrypted\x18\x01 \x01(\fR\rdataEncrypted\x12.\n" +
	"\x13data_format_version\x18\x02 \x01(\x05R\x11dataFormatVersion\x12'\n" +
	"\x0ftitle_encrypted\x18\x03 \x01(\fR\x0etitleEncrypted\"\xb2\x01\n" +
	"\x13UpdateSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12%\n" +
	"\x0edata_encrypted\x18\x02 \x01(\fR\rdataEncrypted\x12.\n" +
	"\x13data_format_version\x18\x03 \x01(\x05R\x11dataFormatVersion\x12'\n" +
	"\x0ftitle_encrypted\x18\x04 \x01(\fR\x0etitleEncrypted\"2\n" +
	"\x13DeleteSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"8\n" +
	"\x19ListSecretVersionsRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"V\n" +
	"\x1aListSecretVersionsResponse\x128\n" +
	"\bversions\x18\x01 \x03(\v2\x1c.gophkeeper.v1.SecretVersionR\bversions\"b\n" +
	"\x17GetSecretVersionRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12*\n" +
	"\x11secret_version_id\x18\x02 \x01(\tR\x0fsecretVersionId\"e\n" +
	"\x1aDeleteSecretVersionRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12*\n" +
	"\x11secret_version_id\x18\x02 \x01(\tR\x0fsecretVersionId\"I\n" +
	"\x1bDeleteSecretVersionResponse\x12*\n" +
	"\x11secret_version_id\x18\x01 \x01(\tR\x0fsecretVersionId\"f\n" +
	"\x1bRestoreSecretVersionRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12*\n" +
	"\x11secret_version_id\x18\x02 \x01(\tR\x0fsecretVersionId\"J\n" +
	"\x1cRestoreSecretVersionResponse\x12*\n" +
	"\x11secret_version_id\x18\x01 \x01(\tR\x0fsecretVersionId\"\xcb\x02\n" +
	"\x11AttachmentSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11secret_version_id\x18\x02 \x01(\tR\x0fsecretVersionId\x12.\n" +
	"\x13data_format_version\x18\x03 \x01(\x05R\x11dataFormatVersion\x12.\n" +
	"\x13info_format_version\x18\x04 \x01(\x05R\x11infoFormatVersion\x12%\n" +
	"\x0einfo_encrypted\x18\x05 \x01(\fR\rinfoEncrypted\x12\x1b\n" +
	"\tinfo_size\x18\x06 \x01(\x05R\binfoSize\x12\x1b\n" +
	"\tdata_size\x18\a \x01(\x05R\bdataSize\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xeb\x02\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11secret_version_id\x18\x02 \x01(\tR\x0fsecretVersionId\x12.\n" +
	"\x13data_format_version\x18\x03 \x01(\x05R\x11dataFormatVersion\x12.\n" +
	"\x13info_format_version\x18\x04 \x01(\x05R\x11infoFormatVersion\x12%\n" +
	"\x0einfo_encrypted\x18\x05 \x01(\fR\rinfoEncrypted\x12\x1b\n" +
	"\tinfo_size\x18\x06 \x01(\x05R\binfoSize\x12%\n" +
	"\x0edata_encrypted\x18\a \x01(\fR\rdataEncrypted\x12\x1b\n" +
	"\tdata_size\x18\b \x01(\x05R\bdataSize\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"n\n" +
	"\x16ListAttachmentsRequest\x12\x1d\n" +
	"\tsecret_id\x18\x01 \x01(\tH\x00R\bsecretId\x12,\n" +
	"\x11secret_version_id\x18\x02 \x01(\tH\x00R\x0fsecretVersionIdB\a\n" +
	"\x05scope\"]\n" +
	"\x17ListAttachmentsResponse\x12B\n" +
	"\vattachments\x18\x01 \x03(\v2 .gophkeeper.v1.AttachmentSummaryR\vattachments\";\n" +
	"\x14GetAttachmentRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\"\xf3\x01\n" +
	"\x17CreateAttachmentRequest\x12*\n" +
	"\x11secret_version_id\x18\x01 \x01(\tR\x0fsecretVersionId\x12.\n" +
	"\x13data_format_version\x18\x02 \x01(\x05R\x11dataFormatVersion\x12.\n" +
	"\x13info_format_version\x18\x03 \x01(\x05R\x11infoFormatVersion\x12%\n" +
	"\x0einfo_encrypted\x18\x04 \x01(\fR\rinfoEncrypted\x12%\n" +
	"\x0edata_encrypted\x18\x05 \x01(\fR\rdataEncrypted\">\n" +
	"\x17DeleteAttachmentRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId*\x96\x01\n" +
	"\x0fSecretListScope\x12!\n" +
	"\x1dSECRET_LIST_SCOPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSECRET_LIST_SCOPE_ACTIVE_ONLY\x10\x01\x12\"\n" +
	"\x1eSECRET_LIST_SCOPE_DELETED_ONLY\x10\x02\x12\x19\n" +
	"\x15SECRET_LIST_SCOPE_ALL\x10\x032\xd5\v\n" +
	"\x11GophKeeperService\x12?\n" +
	"\x04Ping\x12\x1a.gophkeeper.v1.PingRequest\x1a\x1b.gophkeeper.v1.PingResponse\x12G\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1b.gophkeeper.v1.AuthResponse\x12A\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1b.gophkeeper.v1.AuthResponse\x12O\n" +
	"\fRefreshToken\x12\".gophkeeper.v1.RefreshTokenRequest\x1a\x1b.gophkeeper.v1.AuthResponse\x12T\n" +
	"\vListSecrets\x12!.gophkeeper.v1.ListSecretsRequest\x1a\".gophkeeper.v1.ListSecretsResponse\x12C\n" +
	"\tGetSecret\x12\x1f.gophkeeper.v1.GetSecretRequest\x1a\x15.gophkeeper.v1.Secret\x12I\n" +
	"\fCreateSecret\x12\".gophkeeper.v1.CreateSecretRequest\x1a\x15.gophkeeper.v1.Secret\x12P\n" +
	"\fUpdateSecret\x12\".gophkeeper.v1.UpdateSecretRequest\x1a\x1c.gophkeeper.v1.SecretVersion\x12W\n" +
	"\fDeleteSecret\x12\".gophkeeper.v1.DeleteSecretRequest\x1a#.gophkeeper.v1.DeleteSecretResponse\x12i\n" +
	"\x12ListSecretVersions\x12(.gophkeeper.v1.ListSecretVersionsRequest\x1a).gophkeeper.v1.ListSecretVersionsResponse\x12X\n" +
	"\x10GetSecretVersion\x12&.gophkeeper.v1.GetSecretVersionRequest\x1a\x1c.gophkeeper.v1.SecretVersion\x12l\n" +
	"\x13DeleteSecretVersion\x12).gophkeeper.v1.DeleteSecretVersionRequest\x1a*.gophkeeper.v1.DeleteSecretVersionResponse\x12o\n" +
	"\x14RestoreSecretVersion\x12*.gophkeeper.v1.RestoreSecretVersionRequest\x1a+.gophkeeper.v1.RestoreSecretVersionResponse\x12`\n" +
	"\x0fListAttachments\x12%.gophkeeper.v1.ListAttachmentsRequest\x1a&.gophkeeper.v1.ListAttachmentsResponse\x12O\n" +
	"\rGetAttachment\x12#.gophkeeper.v1.GetAttachmentRequest\x1a\x19.gophkeeper.v1.Attachment\x12U\n" +
	"\x10CreateAttachment\x12&.gophkeeper.v1.CreateAttachmentRequest\x1a\x19.gophkeeper.v1.Attachment\x12c\n" +
	"\x10DeleteAttachment\x12&.gophkeeper.v1.DeleteAttachmentRequest\x1a'.gophkeeper.v1.DeleteAttachmentResponseBIZGgithub.com/coolycow/gophkeeper/internal/proto/gophkeeperpb;gophkeeperpbb\x06proto3"

var (
	file_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_proto_rawDescData
}

var file_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_gophkeeper_proto_goTypes = []any{
	(SecretListScope)(0),                 // 0: gophkeeper.v1.SecretListScope
	(*PingRequest)(nil),                  // 1: gophkeeper.v1.PingRequest
	(*PingResponse)(nil),                 // 2: gophkeeper.v1.PingResponse
	(*DeleteSecretResponse)(nil),         // 3: gophkeeper.v1.DeleteSecretResponse
	(*DeleteAttachmentResponse)(nil),     // 4: gophkeeper.v1.DeleteAttachmentResponse
	(*RegisterRequest)(nil),              // 5: gophkeeper.v1.RegisterRequest
	(*LoginRequest)(nil),                 // 6: gophkeeper.v1.LoginRequest
	(*RefreshTokenRequest)(nil),          // 7: gophkeeper.v1.RefreshTokenRequest
	(*AuthResponse)(nil),                 // 8: gophkeeper.v1.AuthResponse
	(*SecretSummary)(nil),                // 9: gophkeeper.v1.SecretSummary
	(*ListSecretsRequest)(nil),           // 10: gophkeeper.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),          // 11: gophkeeper.v1.ListSecretsResponse
	(*GetSecretRequest)(nil),             // 12: gophkeeper.v1.GetSecretRequest
	(*Secret)(nil),                       // 13: gophkeeper.v1.Secret
	(*SecretVersion)(nil),                // 14: gophkeeper.v1.SecretVersion
	(*CreateSecretRequest)(nil),          // 15: gophkeeper.v1.CreateSecretRequest
	(*UpdateSecretRequest)(nil),          // 16: gophkeeper.v1.UpdateSecretRequest
	(*DeleteSecretRequest)(nil),          // 17: gophkeeper.v1.DeleteSecretRequest
	(*ListSecretVersionsRequest)(nil),    // 18: gophkeeper.v1.ListSecretVersionsRequest
	(*ListSecretVersionsResponse)(nil),   // 19: gophkeeper.v1.ListSecretVersionsResponse
	(*GetSecretVersionRequest)(nil),      // 20: gophkeeper.v1.GetSecretVersionRequest
	(*DeleteSecretVersionRequest)(nil),   // 21: gophkeeper.v1.DeleteSecretVersionRequest
	(*DeleteSecretVersionResponse)(nil),  // 22: gophkeeper.v1.DeleteSecretVersionResponse
	(*RestoreSecretVersionRequest)(nil),  // 23: gophkeeper.v1.RestoreSecretVersionRequest
	(*RestoreSecretVersionResponse)(nil), // 24: gophkeeper.v1.RestoreSecretVersionResponse
	(*AttachmentSummary)(nil),            // 25: gophkeeper.v1.AttachmentSummary
	(*Attachment)(nil),                   // 26: gophkeeper.v1.Attachment
	(*ListAttachmentsRequest)(nil),       // 27: gophkeeper.v1.ListAttachmentsRequest
	(*ListAttachmentsResponse)(nil),      // 28: gophkeeper.v1.ListAttachmentsResponse
	(*GetAttachmentRequest)(nil),         // 29: gophkeeper.v1.GetAttachmentRequest
	(*CreateAttachmentRequest)(nil),      // 30: gophkeeper.v1.CreateAttachmentRequest
	(*DeleteAttachmentRequest)(nil),      // 31: gophkeeper.v1.DeleteAttachmentRequest
	(*timestamppb.Timestamp)(nil),        // 32: google.protobuf.Timestamp
}
var file_gophkeeper_proto_depIdxs = []int32{
	32, // 0: gophkeeper.v1.AuthResponse.expires_at:type_name -> google.protobuf.Timestamp
	32, // 1: gophkeeper.v1.SecretSummary.updated_at:type_name -> google.protobuf.Timestamp
	32, // 2: gophkeeper.v1.SecretSummary.deleted_at:type_name -> google.protobuf.Timestamp
	32, // 3: gophkeeper.v1.SecretSummary.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: gophkeeper.v1.ListSecretsRequest.list_scope:type_name -> gophkeeper.v1.SecretListScope
	9,  // 5: gophkeeper.v1.ListSecretsResponse.secrets:type_name -> gophkeeper.v1.SecretSummary
	32, // 6: gophkeeper.v1.Secret.created_at:type_name -> google.protobuf.Timestamp
	32, // 7: gophkeeper.v1.Secret.updated_at:type_name -> google.protobuf.Timestamp
	32, // 8: gophkeeper.v1.Secret.deleted_at:type_name -> google.protobuf.Timestamp
	14, // 9: gophkeeper.v1.Secret.current_version:type_name -> gophkeeper.v1.SecretVersion
	14, // 10: gophkeeper.v1.Secret.secret_versions:type_name -> gophkeeper.v1.SecretVersion
	32, // 11: gophkeeper.v1.SecretVersion.created_at:type_name -> google.protobuf.Timestamp
	32, // 12: gophkeeper.v1.SecretVersion.updated_at:type_name -> google.protobuf.Timestamp
	32, // 13: gophkeeper.v1.SecretVersion.deleted_at:type_name -> google.protobuf.Timestamp
	14, // 14: gophkeeper.v1.ListSecretVersionsResponse.versions:type_name -> gophkeeper.v1.SecretVersion
	32, // 15: gophkeeper.v1.AttachmentSummary.created_at:type_name -> google.protobuf.Timestamp
	32, // 16: gophkeeper.v1.Attachment.created_at:type_name -> google.protobuf.Timestamp
	25, // 17: gophkeeper.v1.ListAttachmentsResponse.attachments:type_name -> gophkeeper.v1.AttachmentSummary
	1,  // 18: gophkeeper.v1.GophKeeperService.Ping:input_type -> gophkeeper.v1.PingRequest
	5,  // 19: gophkeeper.v1.GophKeeperService.Register:input_type -> gophkeeper.v1.RegisterRequest
	6,  // 20: gophkeeper.v1.GophKeeperService.Login:input_type -> gophkeeper.v1.LoginRequest
	7,  // 21: gophkeeper.v1.GophKeeperService.RefreshToken:input_type -> gophkeeper.v1.RefreshTokenRequest
	10, // 22: gophkeeper.v1.GophKeeperService.ListSecrets:input_type -> gophkeeper.v1.ListSecretsRequest
	12, // 23: gophkeeper.v1.GophKeeperService.GetSecret:input_type -> gophkeeper.v1.GetSecretRequest
	15, // 24: gophkeeper.v1.GophKeeperService.CreateSecret:input_type -> gophkeeper.v1.CreateSecretRequest
	16, // 25: gophkeeper.v1.GophKeeperService.UpdateSecret:input_type -> gophkeeper.v1.UpdateSecretRequest
	17, // 26: gophkeeper.v1.GophKeeperService.DeleteSecret:input_type -> gophkeeper.v1.DeleteSecretRequest
	18, // 27: gophkeeper.v1.GophKeeperService.ListSecretVersions:input_type -> gophkeeper.v1.ListSecretVersionsRequest
	20, // 28: gophkeeper.v1.GophKeeperService.GetSecretVersion:input_type -> gophkeeper.v1.GetSecretVersionRequest
	21, // 29: gophkeeper.v1.GophKeeperService.DeleteSecretVersion:input_type -> gophkeeper.v1.DeleteSecretVersionRequest
	23, // 30: gophkeeper.v1.GophKeeperService.RestoreSecretVersion:input_type -> gophkeeper.v1.RestoreSecretVersionRequest
	27, // 31: gophkeeper.v1.GophKeeperService.ListAttachments:input_type -> gophkeeper.v1.ListAttachmentsRequest
	29, // 32: gophkeeper.v1.GophKeeperService.GetAttachment:input_type -> gophkeeper.v1.GetAttachmentRequest
	30, // 33: gophkeeper.v1.GophKeeperService.CreateAttachment:input_type -> gophkeeper.v1.CreateAttachmentRequest
	31, // 34: gophkeeper.v1.GophKeeperService.DeleteAttachment:input_type -> gophkeeper.v1.DeleteAttachmentRequest
	2,  // 35: gophkeeper.v1.GophKeeperService.Ping:output_type -> gophkeeper.v1.PingResponse
	8,  // 36: gophkeeper.v1.GophKeeperService.Register:output_type -> gophkeeper.v1.AuthResponse
	8,  // 37: gophkeeper.v1.GophKeeperService.Login:output_type -> gophkeeper.v1.AuthResponse
	8,  // 38: gophkeeper.v1.GophKeeperService.RefreshToken:output_type -> gophkeeper.v1.AuthResponse
	11, // 39: gophkeeper.v1.GophKeeperService.ListSecrets:output_type -> gophkeeper.v1.ListSecretsResponse
	13, // 40: gophkeeper.v1.GophKeeperService.GetSecret:output_type -> gophkeeper.v1.Secret
	13, // 41: gophkeeper.v1.GophKeeperService.CreateSecret:output_type -> gophkeeper.v1.Secret
	14, // 42: gophkeeper.v1.GophKeeperService.UpdateSecret:output_type -> gophkeeper.v1.SecretVersion
	3,  // 43: gophkeeper.v1.GophKeeperService.DeleteSecret:output_type -> gophkeeper.v1.DeleteSecretResponse
	19, // 44: gophkeeper.v1.GophKeeperService.ListSecretVersions:output_type -> gophkeeper.v1.ListSecretVersionsResponse
	14, // 45: gophkeeper.v1.GophKeeperService.GetSecretVersion:output_type -> gophkeeper.v1.SecretVersion
	22, // 46: gophkeeper.v1.GophKeeperService.DeleteSecretVersion:output_type -> gophkeeper.v1.DeleteSecretVersionResponse
	24, // 47: gophkeeper.v1.GophKeeperService.RestoreSecretVersion:output_type -> gophkeeper.v1.RestoreSecretVersionResponse
	28, // 48: gophkeeper.v1.GophKeeperService.ListAttachments:output_type -> gophkeeper.v1.ListAttachmentsResponse
	26, // 49: gophkeeper.v1.GophKeeperService.GetAttachment:output_type -> gophkeeper.v1.Attachment
	26, // 50: gophkeeper.v1.GophKeeperService.CreateAttachment:output_type -> gophkeeper.v1.Attachment
	4,  // 51: gophkeeper.v1.GophKeeperService.DeleteAttachment:output_type -> gophkeeper.v1.DeleteAttachmentResponse
	35, // [35:52] is the sub-list for method output_type
	18, // [18:35] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	file_gophkeeper_proto_msgTypes[26].OneofWrappers = []any{
		(*ListAttachmentsRequest_SecretId)(nil),
		(*ListAttachmentsRequest_SecretVersionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		EnumInfos:         file_gophkeeper_proto_enumTypes,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
